language: generic 
sudo: required

services:
  - docker

before_install:
  - docker build -t orynbayev/docker-react -f Dockerfile.dev .
 
script:
  - docker run -e CI=true orynbayev/docker-react npm run test -- --coverage