language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t orynbayev/docker-react -f Dockerfile.dev .
 
script:
  - docker run -e CI=true orynbayev/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: eu-central-1
  name: react-app
  env: ReactApp-env
  bucket_name: elasticbeanstalk-eu-central-1-285767009009
  bucket_path: docker-react
  skip_cleanup: true
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY